version: "3.9"

services:
  mongo:
    image: mongo
    container_name: form_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: form_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/formdb
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: form_frontend
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host", "--port", "5173"]
    depends_on:
      - backend

volumes:
  mongo_data:
